### ISSUE TITLE
About evaluation on MICC Florence dataset

### ISSUE THREAD

**Issue by MariaWang96** [yongbinkwon/3d_face_reconstruction#1]
Thanks for your codes, I find some help for evaluating results on Florence.

But I don't make clear which evaluation process on Florence dataset that you have chosen? From obj. to images with different poses, then input images to network for reconstruction. Then compare between 3D vertices? Or rendered images? Hope for your reply~

**Comment by yongbinkwon** [comment]
Hi! I’m sorry the code is such a mess, this is actually my master’s thesis and the repo is supposed to be private until I’m done (a few more weeks or so). 

In regards to your question: I render the meshes as images at different poses, then compare the output from the network with the obj from florence
